import React, { useState } from 'react'
import { useAppStore } from '@/store/appStore'
import { useTranslation } from '@/i18n/useTranslation'

interface Template {
  id: string
  name: string
  icon: string
  desc: string
  color: string
  features: string[]
}

const TEMPLATES: Template[] = [
  { id: 'react-vite', name: 'React + Vite', icon: '⚛️', desc: 'Fast SPA with TypeScript', color: '#61DAFB', features: ['React 18', 'Vite 5', 'TypeScript', 'ESLint'] },
  { id: 'nextjs', name: 'Next.js 14', icon: '▲', desc: 'Full-stack React framework', color: '#ffffff', features: ['App Router', 'TypeScript', 'Tailwind CSS', 'ESLint'] },
  { id: 'electron-react', name: 'Electron + React', icon: '⚡', desc: 'Desktop app with React', color: '#9FEAF9', features: ['Electron 31', 'React 18', 'TypeScript', 'electron-vite'] },
  { id: 'vue3', name: 'Vue 3', icon: '🟩', desc: 'Progressive framework', color: '#42B883', features: ['Vue 3', 'Vite', 'TypeScript', 'Pinia'] },
  { id: 'node-api', name: 'Node.js API', icon: '🟢', desc: 'REST API with Express', color: '#83CD29', features: ['Express 5', 'TypeScript', 'Zod', 'Prisma'] },
  { id: 'python-fastapi', name: 'Python FastAPI', icon: '🐍', desc: 'Modern Python API', color: '#009688', features: ['FastAPI', 'Pydantic v2', 'SQLModel', 'Uvicorn'] }
]

interface ProjectFile {
  path: string
  content: string
}

function getTemplateFiles(templateId: string, projectName: string): ProjectFile[] {
  if (templateId === 'react-vite') {
    return [
      { path: 'package.json', content: `{"name":"${projectName}","version":"0.1.0","scripts":{"dev":"vite","build":"tsc && vite build","preview":"vite preview"},"dependencies":{"react":"^18.3.0","react-dom":"^18.3.0"},"devDependencies":{"@types/react":"^18.3.0","@types/react-dom":"^18.3.0","@vitejs/plugin-react":"^4.3.0","typescript":"^5.5.0","vite":"^5.4.0"}}` },
      { path: 'tsconfig.json', content: `{"compilerOptions":{"target":"ES2020","lib":["ES2020","DOM"],"module":"ESNext","moduleResolution":"bundler","jsx":"react-jsx","strict":true,"outDir":"dist"},"include":["src"]}` },
      { path: 'vite.config.ts', content: `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()]\n})` },
      { path: 'index.html', content: `<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8" /><title>${projectName}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>` },
      { path: 'src/main.tsx', content: `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n)` },
      { path: 'src/App.tsx', content: `import React from 'react'\n\nfunction App() {\n  return (\n    <div>\n      <h1>${projectName}</h1>\n      <p>Built with React + Vite</p>\n    </div>\n  )\n}\n\nexport default App` },
      { path: 'src/App.css', content: `h1 { color: #61DAFB; }` },
      { path: '.gitignore', content: `node_modules\ndist\n.DS_Store` },
      { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio Coding Agent.\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`` }
    ]
  }

  if (templateId === 'nextjs') {
    return [
      { path: 'package.json', content: `{"name":"${projectName}","version":"0.1.0","scripts":{"dev":"next dev","build":"next build","start":"next start","lint":"next lint"},"dependencies":{"next":"14.2.0","react":"^18","react-dom":"^18"},"devDependencies":{"@types/node":"^20","@types/react":"^18","typescript":"^5","tailwindcss":"^3","eslint":"^8","eslint-config-next":"14.2.0"}}` },
      { path: 'tsconfig.json', content: `{"compilerOptions":{"target":"ES2017","lib":["dom","dom.iterable","esnext"],"allowJs":true,"skipLibCheck":true,"strict":true,"module":"esnext","moduleResolution":"bundler","jsx":"preserve","incremental":true,"plugins":[{"name":"next"}],"paths":{"@/*":["./src/*"]}},"include":["next-env.d.ts","**/*.ts","**/*.tsx"],"exclude":["node_modules"]}` },
      { path: 'next.config.ts', content: `import type { NextConfig } from 'next'\n\nconst nextConfig: NextConfig = {}\n\nexport default nextConfig` },
      { path: 'tailwind.config.ts', content: `import type { Config } from 'tailwindcss'\n\nconst config: Config = {\n  content: ['./src/**/*.{ts,tsx}'],\n  theme: { extend: {} },\n  plugins: []\n}\n\nexport default config` },
      { path: 'src/app/layout.tsx', content: `import type { Metadata } from 'next'\n\nexport const metadata: Metadata = {\n  title: '${projectName}',\n  description: 'Generated by Omar AI Studio'\n}\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}` },
      { path: 'src/app/page.tsx', content: `export default function Home() {\n  return (\n    <main>\n      <h1>${projectName}</h1>\n      <p>Built with Next.js 14</p>\n    </main>\n  )\n}` },
      { path: 'src/app/globals.css', content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;` },
      { path: '.gitignore', content: `node_modules\n.next\ndist\n.DS_Store` },
      { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio.\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`` }
    ]
  }

  if (templateId === 'electron-react') {
    return [
      { path: 'package.json', content: `{"name":"${projectName}","version":"0.1.0","main":"dist-electron/main.js","scripts":{"dev":"electron-vite dev","build":"electron-vite build","preview":"electron-vite preview"},"dependencies":{"react":"^18.3.0","react-dom":"^18.3.0"},"devDependencies":{"electron":"^31.0.0","electron-vite":"^2.3.0","@types/react":"^18.3.0","@vitejs/plugin-react":"^4.3.0","typescript":"^5.5.0"}}` },
      { path: 'electron.vite.config.ts', content: `import { defineConfig, externalizeDepsPlugin } from 'electron-vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  main: { plugins: [externalizeDepsPlugin()] },\n  preload: { plugins: [externalizeDepsPlugin()] },\n  renderer: { plugins: [react()] }\n})` },
      { path: 'electron/main.ts', content: `import { app, BrowserWindow } from 'electron'\nimport { join } from 'path'\n\nfunction createWindow() {\n  const win = new BrowserWindow({\n    width: 1280,\n    height: 800,\n    webPreferences: { preload: join(__dirname, '../preload/index.js'), contextIsolation: true }\n  })\n  if (process.env.VITE_DEV_SERVER_URL) win.loadURL(process.env.VITE_DEV_SERVER_URL)\n  else win.loadFile(join(__dirname, '../renderer/index.html'))\n}\n\napp.whenReady().then(createWindow)` },
      { path: 'electron/preload.ts', content: `import { contextBridge } from 'electron'\n\ncontextBridge.exposeInMainWorld('api', {\n  version: process.version\n})` },
      { path: 'src/renderer/src/App.tsx', content: `import React from 'react'\n\nfunction App() {\n  return (\n    <div>\n      <h1>${projectName}</h1>\n      <p>Built with Electron + React</p>\n    </div>\n  )\n}\n\nexport default App` },
      { path: 'src/renderer/src/main.tsx', content: `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)` },
      { path: 'src/renderer/index.html', content: `<!DOCTYPE html>\n<html>\n<head><title>${projectName}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>` },
      { path: '.gitignore', content: `node_modules\ndist\ndist-electron\n.DS_Store` },
      { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio.\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`` }
    ]
  }

  if (templateId === 'vue3') {
    return [
      { path: 'package.json', content: `{"name":"${projectName}","version":"0.1.0","scripts":{"dev":"vite","build":"vue-tsc && vite build","preview":"vite preview"},"dependencies":{"vue":"^3.4.0","pinia":"^2.1.0"},"devDependencies":{"@vitejs/plugin-vue":"^5.0.0","typescript":"^5.5.0","vite":"^5.4.0","vue-tsc":"^2.0.0"}}` },
      { path: 'vite.config.ts', content: `import { defineConfig } from 'vite'\nimport vue from '@vitejs/plugin-vue'\n\nexport default defineConfig({\n  plugins: [vue()]\n})` },
      { path: 'tsconfig.json', content: `{"compilerOptions":{"target":"ES2020","module":"ESNext","moduleResolution":"bundler","strict":true,"jsx":"preserve"},"include":["src/**/*.ts","src/**/*.vue"]}` },
      { path: 'index.html', content: `<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8" /><title>${projectName}</title></head>\n<body><div id="app"></div><script type="module" src="/src/main.ts"></script></body>\n</html>` },
      { path: 'src/main.ts', content: `import { createApp } from 'vue'\nimport { createPinia } from 'pinia'\nimport App from './App.vue'\n\nconst app = createApp(App)\napp.use(createPinia())\napp.mount('#app')` },
      { path: 'src/App.vue', content: `<template>\n  <div>\n    <h1>${projectName}</h1>\n    <p>Built with Vue 3</p>\n  </div>\n</template>\n\n<script setup lang="ts">\n// Your setup here\n</script>` },
      { path: 'src/stores/counter.ts', content: `import { defineStore } from 'pinia'\n\nexport const useCounterStore = defineStore('counter', {\n  state: () => ({ count: 0 }),\n  actions: { increment() { this.count++ } }\n})` },
      { path: '.gitignore', content: `node_modules\ndist\n.DS_Store` },
      { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio.\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`` }
    ]
  }

  if (templateId === 'node-api') {
    return [
      { path: 'package.json', content: `{"name":"${projectName}","version":"0.1.0","scripts":{"dev":"tsx watch src/index.ts","build":"tsc","start":"node dist/index.js"},"dependencies":{"express":"^5.0.0","zod":"^3.23.0"},"devDependencies":{"@types/express":"^5.0.0","@types/node":"^22.0.0","tsx":"^4.17.0","typescript":"^5.5.0"}}` },
      { path: 'tsconfig.json', content: `{"compilerOptions":{"target":"ES2022","module":"CommonJS","moduleResolution":"node","strict":true,"outDir":"dist","rootDir":"src"},"include":["src"]}` },
      { path: 'src/index.ts', content: `import express from 'express'\n\nconst app = express()\nconst PORT = process.env.PORT || 3000\n\napp.use(express.json())\n\napp.get('/health', (_req, res) => {\n  res.json({ status: 'ok', project: '${projectName}' })\n})\n\napp.listen(PORT, () => {\n  console.log(\`Server running on http://localhost:\${PORT}\`)\n})` },
      { path: 'src/routes/index.ts', content: `import { Router } from 'express'\n\nexport const router = Router()\n\nrouter.get('/', (_req, res) => {\n  res.json({ message: 'Welcome to ${projectName}' })\n})` },
      { path: 'src/middleware/error.ts', content: `import type { Request, Response, NextFunction } from 'express'\n\nexport function errorHandler(err: Error, _req: Request, res: Response, _next: NextFunction) {\n  console.error(err.stack)\n  res.status(500).json({ error: err.message })\n}` },
      { path: '.gitignore', content: `node_modules\ndist\n.env\n.DS_Store` },
      { path: '.env.example', content: `PORT=3000\nDATABASE_URL=postgresql://user:password@localhost:5432/db` },
      { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio.\n\n## Development\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`` }
    ]
  }

  // python-fastapi
  return [
    { path: 'requirements.txt', content: `fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\npydantic>=2.8.0\nsqlmodel>=0.0.21\npython-dotenv>=1.0.0` },
    { path: 'main.py', content: `from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI(title="${projectName}", version="0.1.0")\n\nclass HealthResponse(BaseModel):\n    status: str\n    project: str\n\n@app.get("/health", response_model=HealthResponse)\ndef health():\n    return {"status": "ok", "project": "${projectName}"}` },
    { path: 'src/__init__.py', content: `` },
    { path: 'src/models.py', content: `from sqlmodel import SQLModel, Field\nfrom typing import Optional\n\nclass ItemBase(SQLModel):\n    name: str\n    description: Optional[str] = None\n\nclass Item(ItemBase, table=True):\n    id: Optional[int] = Field(default=None, primary_key=True)` },
    { path: 'src/routes.py', content: `from fastapi import APIRouter\n\nrouter = APIRouter(prefix="/api/v1")\n\n@router.get("/items")\ndef list_items():\n    return []` },
    { path: '.env.example', content: `DATABASE_URL=sqlite:///./database.db` },
    { path: '.gitignore', content: `__pycache__\n*.pyc\n.env\nvenv\n*.db` },
    { path: 'README.md', content: `# ${projectName}\n\nGenerated by Omar AI Studio.\n\n## Development\n\n\`\`\`bash\npip install -r requirements.txt\nuvicorn main:app --reload\n\`\`\`` }
  ]
}

type WizardStep = 'template' | 'details' | 'creating' | 'done'

export function CreateProjectWizard(): React.ReactElement {
  const { setCodingView, setCodingProjectPath } = useAppStore()
  const { t, isAr } = useTranslation()

  const [step, setStep] = useState<WizardStep>('template')
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null)
  const [projectName, setProjectName] = useState('')
  const [savePath, setSavePath] = useState<string>(
    typeof window !== 'undefined' && window.api ? '' : '/Users'
  )
  const [description, setDescription] = useState('')
  const [enabledFeatures, setEnabledFeatures] = useState<Set<string>>(new Set())
  const [progress, setProgress] = useState(0)
  const [createdFiles, setCreatedFiles] = useState<string[]>([])
  const [statusMessage, setStatusMessage] = useState('')
  const [finalPath, setFinalPath] = useState('')

  const fontUi = isAr ? 'var(--font-ar)' : 'var(--font-ui)'

  const handleSelectTemplate = (tmpl: Template) => {
    setSelectedTemplate(tmpl)
    setEnabledFeatures(new Set(tmpl.features))
    setStep('details')
  }

  const handleBrowse = async () => {
    if (typeof window === 'undefined' || !window.api) return
    const result = await window.api.dialog.showOpenDialog({ properties: ['openDirectory'] })
    if (!result.canceled && result.filePaths && result.filePaths[0]) {
      setSavePath(result.filePaths[0])
    }
  }

  const handleCreate = async () => {
    if (!projectName.trim() || !selectedTemplate) return
    setStep('creating')
    setProgress(0)
    setCreatedFiles([])

    const files = getTemplateFiles(selectedTemplate.id, projectName.trim())
    const projectPath = `${savePath}/${projectName.trim()}`
    setFinalPath(projectPath)

    setStatusMessage(t.generatingFiles || 'Generating files...')

    for (let i = 0; i < files.length; i++) {
      const file = files[i]
      const pct = Math.round(((i + 1) / files.length) * 100)
      setStatusMessage(t.writingFiles || 'Writing to disk...')

      try {
        if (typeof window !== 'undefined' && window.api?.fs) {
          await window.api.fs.writeFile(`${projectPath}/${file.path}`, file.content)
        }
      } catch {
        // Electron FS not available in browser mode — continue silently
      }

      // Artificial delay to feel real
      await new Promise((r) => setTimeout(r, 200 + Math.random() * 200))
      setCreatedFiles((prev) => [...prev, file.path])
      setProgress(pct)
    }

    setStatusMessage('')
    setCodingProjectPath(projectPath)
    setStep('done')
  }

  const handleReviewCode = () => {
    setCodingView('lab')
  }

  const handleStartNew = () => {
    setStep('template')
    setSelectedTemplate(null)
    setProjectName('')
    setDescription('')
    setProgress(0)
    setCreatedFiles([])
  }

  const handleCopyPath = () => {
    if (finalPath) navigator.clipboard.writeText(finalPath).catch(() => {})
  }

  // Step 1: Choose Template
  if (step === 'template') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', background: 'var(--bg-primary)' }} dir={isAr ? 'rtl' : 'ltr'}>
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--border-subtle)', background: 'var(--bg-secondary)', flexShrink: 0 }}>
          <div style={{ fontWeight: 700, fontSize: 18, color: 'var(--text-primary)', fontFamily: fontUi }}>
            ✨ {isAr ? 'مشروع جديد' : 'New Project'}
          </div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4, fontFamily: fontUi }}>
            {t.chooseTemplate || 'Choose Template'}
          </div>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: 24 }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, maxWidth: 900 }}>
            {TEMPLATES.map((tmpl) => (
              <div
                key={tmpl.id}
                onClick={() => handleSelectTemplate(tmpl)}
                style={{
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border-subtle)',
                  borderRadius: 'var(--radius-lg)',
                  padding: 20,
                  cursor: 'pointer',
                  transition: 'all 0.15s ease',
                  position: 'relative',
                  overflow: 'hidden'
                }}
                onMouseEnter={(e) => {
                  (e.currentTarget as HTMLDivElement).style.borderColor = `${tmpl.color}40`
                  ;(e.currentTarget as HTMLDivElement).style.background = 'var(--bg-card-hover)'
                }}
                onMouseLeave={(e) => {
                  (e.currentTarget as HTMLDivElement).style.borderColor = 'var(--border-subtle)'
                  ;(e.currentTarget as HTMLDivElement).style.background = 'var(--bg-card)'
                }}
              >
                <div style={{ fontSize: 32, marginBottom: 10 }}>{tmpl.icon}</div>
                <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--text-primary)', fontFamily: fontUi, marginBottom: 4 }}>
                  {tmpl.name}
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: fontUi, marginBottom: 12 }}>
                  {tmpl.desc}
                </div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                  {tmpl.features.map((f) => (
                    <span key={f} style={{ padding: '2px 7px', background: `${tmpl.color}12`, border: `1px solid ${tmpl.color}25`, borderRadius: 10, fontSize: 10, color: tmpl.color, fontFamily: fontUi }}>
                      {f}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  // Step 2: Project Details
  if (step === 'details' && selectedTemplate) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', background: 'var(--bg-primary)' }} dir={isAr ? 'rtl' : 'ltr'}>
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--border-subtle)', background: 'var(--bg-secondary)', flexShrink: 0, display: 'flex', alignItems: 'center', gap: 12 }}>
          <button
            onClick={() => setStep('template')}
            style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: 18, padding: 0, lineHeight: 1 }}
          >
            ←
          </button>
          <div>
            <div style={{ fontWeight: 700, fontSize: 18, color: 'var(--text-primary)', fontFamily: fontUi }}>
              {selectedTemplate.icon} {selectedTemplate.name}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2, fontFamily: fontUi }}>
              {t.projectDetails || 'Project Details'}
            </div>
          </div>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: 24 }}>
          <div style={{ maxWidth: 600, display: 'flex', flexDirection: 'column', gap: 20 }}>
            {/* Project Name */}
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, fontFamily: fontUi }}>
                {t.projectName2 || 'Project Name'}
              </label>
              <input
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="my-awesome-project"
                style={{
                  width: '100%',
                  background: 'var(--bg-input)',
                  border: '1px solid var(--border-medium)',
                  borderRadius: 'var(--radius-md)',
                  padding: '10px 14px',
                  color: 'var(--text-primary)',
                  fontSize: 14,
                  outline: 'none',
                  fontFamily: fontUi
                }}
              />
            </div>

            {/* Save Location */}
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, fontFamily: fontUi }}>
                {t.saveLocation || 'Save Location'}
              </label>
              <div style={{ display: 'flex', gap: 8 }}>
                <input
                  value={savePath}
                  onChange={(e) => setSavePath(e.target.value)}
                  placeholder="/Users/you/projects"
                  style={{
                    flex: 1,
                    background: 'var(--bg-input)',
                    border: '1px solid var(--border-medium)',
                    borderRadius: 'var(--radius-md)',
                    padding: '10px 14px',
                    color: 'var(--text-primary)',
                    fontSize: 13,
                    outline: 'none',
                    fontFamily: 'monospace'
                  }}
                />
                <button
                  onClick={handleBrowse}
                  style={{
                    padding: '10px 16px',
                    background: 'var(--bg-card)',
                    border: '1px solid var(--border-medium)',
                    borderRadius: 'var(--radius-md)',
                    color: 'var(--text-secondary)',
                    fontSize: 12,
                    cursor: 'pointer',
                    fontFamily: fontUi,
                    whiteSpace: 'nowrap'
                  }}
                >
                  {t.browse || 'Browse'}
                </button>
              </div>
              {projectName && savePath && (
                <div style={{ marginTop: 6, fontSize: 11, color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                  → {savePath}/{projectName}
                </div>
              )}
            </div>

            {/* Description */}
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, fontFamily: fontUi }}>
                {isAr ? 'الوصف (اختياري)' : 'Description (optional)'}
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder={isAr ? 'صف مشروعك باختصار...' : 'Brief description of your project...'}
                rows={3}
                style={{
                  width: '100%',
                  background: 'var(--bg-input)',
                  border: '1px solid var(--border-medium)',
                  borderRadius: 'var(--radius-md)',
                  padding: '10px 14px',
                  color: 'var(--text-primary)',
                  fontSize: 13,
                  outline: 'none',
                  resize: 'vertical',
                  fontFamily: fontUi,
                  lineHeight: 1.5
                }}
              />
            </div>

            {/* Features */}
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 10, fontFamily: fontUi }}>
                {t.features || 'Features'}
              </label>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {selectedTemplate.features.map((feat) => {
                  const enabled = enabledFeatures.has(feat)
                  return (
                    <div
                      key={feat}
                      onClick={() => {
                        setEnabledFeatures((prev) => {
                          const next = new Set(prev)
                          if (next.has(feat)) next.delete(feat)
                          else next.add(feat)
                          return next
                        })
                      }}
                      style={{
                        padding: '6px 14px',
                        background: enabled ? `${selectedTemplate.color}15` : 'var(--bg-card)',
                        border: `1px solid ${enabled ? `${selectedTemplate.color}40` : 'var(--border-subtle)'}`,
                        borderRadius: 20,
                        fontSize: 12,
                        color: enabled ? selectedTemplate.color : 'var(--text-muted)',
                        cursor: 'pointer',
                        fontFamily: fontUi,
                        fontWeight: enabled ? 600 : 400,
                        transition: 'all 0.12s ease',
                        userSelect: 'none'
                      }}
                    >
                      {enabled ? '✓ ' : ''}{feat}
                    </div>
                  )
                })}
              </div>
            </div>

            {/* Buttons */}
            <div style={{ display: 'flex', gap: 10, paddingTop: 8 }}>
              <button
                onClick={() => setStep('template')}
                style={{
                  padding: '10px 20px',
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border-medium)',
                  borderRadius: 'var(--radius-md)',
                  color: 'var(--text-secondary)',
                  fontSize: 13,
                  cursor: 'pointer',
                  fontFamily: fontUi
                }}
              >
                ← {t.cancel || 'Back'}
              </button>
              <button
                onClick={handleCreate}
                disabled={!projectName.trim() || !savePath.trim()}
                style={{
                  padding: '10px 24px',
                  background: !projectName.trim() || !savePath.trim() ? 'rgba(124,111,247,0.05)' : 'rgba(124,111,247,0.15)',
                  border: `1px solid ${!projectName.trim() || !savePath.trim() ? 'rgba(124,111,247,0.1)' : 'rgba(124,111,247,0.4)'}`,
                  borderRadius: 'var(--radius-md)',
                  color: !projectName.trim() || !savePath.trim() ? 'var(--text-muted)' : 'var(--agent-chief)',
                  fontSize: 13,
                  fontWeight: 700,
                  cursor: !projectName.trim() || !savePath.trim() ? 'not-allowed' : 'pointer',
                  fontFamily: fontUi
                }}
              >
                {t.createProject || '✨ Create Project'}
              </button>
            </div>
          </div>
        </div>
      </div>
    )
  }

  // Step 3: Creating (progress)
  if (step === 'creating') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', background: 'var(--bg-primary)', alignItems: 'center', justifyContent: 'center' }} dir={isAr ? 'rtl' : 'ltr'}>
        <div style={{ maxWidth: 500, width: '100%', padding: 32, display: 'flex', flexDirection: 'column', gap: 20 }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: 40, marginBottom: 16, animation: 'spin 2s linear infinite', display: 'inline-block' }}>⚙️</div>
            <div style={{ fontWeight: 700, fontSize: 20, color: 'var(--text-primary)', fontFamily: fontUi, marginBottom: 4 }}>
              {t.creating || 'Creating...'}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: 'monospace' }}>
              {projectName}
            </div>
          </div>

          {/* Progress bar */}
          <div>
            <div style={{ height: 6, background: 'var(--border-subtle)', borderRadius: 3, overflow: 'hidden', marginBottom: 8 }}>
              <div style={{ height: '100%', width: `${progress}%`, background: 'var(--agent-chief)', borderRadius: 3, transition: 'width 0.3s ease' }} />
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-muted)', fontFamily: fontUi }}>
              <span>{statusMessage}</span>
              <span>{progress}%</span>
            </div>
          </div>

          {/* File log */}
          <div style={{
            background: 'var(--bg-secondary)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: 12,
            maxHeight: 200,
            overflowY: 'auto',
            fontFamily: 'monospace',
            fontSize: 11
          }}>
            {createdFiles.map((f, i) => (
              <div key={i} style={{ color: '#55EFC4', marginBottom: 2 }}>
                ✓ {f}
              </div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  // Step 4: Done
  if (step === 'done') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', background: 'var(--bg-primary)', alignItems: 'center', justifyContent: 'center' }} dir={isAr ? 'rtl' : 'ltr'}>
        <div style={{ maxWidth: 500, width: '100%', padding: 32, display: 'flex', flexDirection: 'column', gap: 20, alignItems: 'center', textAlign: 'center' }}>
          <div style={{ fontSize: 56 }}>🎉</div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 22, color: 'var(--text-primary)', fontFamily: fontUi, marginBottom: 6 }}>
              {t.projectCreated || 'Project Created!'}
            </div>
            <div style={{ fontSize: 13, color: 'var(--text-secondary)', fontFamily: fontUi }}>
              {projectName}
            </div>
          </div>

          {/* Path display */}
          <div style={{
            background: 'var(--bg-secondary)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '10px 16px',
            width: '100%',
            display: 'flex',
            alignItems: 'center',
            gap: 8
          }}>
            <span style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: 'monospace', flex: 1, textAlign: 'left', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {finalPath}
            </span>
            <button
              onClick={handleCopyPath}
              style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: 14, padding: '2px 4px', flexShrink: 0 }}
              title="Copy path"
            >
              📋
            </button>
          </div>

          <div style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: fontUi }}>
            {createdFiles.length} {t.filesCreated || 'files created'}
          </div>

          {/* Action buttons */}
          <div style={{ display: 'flex', gap: 10, width: '100%', flexWrap: 'wrap', justifyContent: 'center' }}>
            <button
              onClick={handleCopyPath}
              style={{
                padding: '10px 20px',
                background: 'var(--bg-card)',
                border: '1px solid var(--border-medium)',
                borderRadius: 'var(--radius-md)',
                color: 'var(--text-secondary)',
                fontSize: 12,
                cursor: 'pointer',
                fontFamily: fontUi
              }}
            >
              {t.openInFinder || '📁 Open in Finder'}
            </button>
            <button
              onClick={handleReviewCode}
              style={{
                padding: '10px 20px',
                background: 'rgba(67,217,173,0.12)',
                border: '1px solid rgba(67,217,173,0.35)',
                borderRadius: 'var(--radius-md)',
                color: '#43D9AD',
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
                fontFamily: fontUi
              }}
            >
              {t.reviewCode || '🔍 Review Code'}
            </button>
            <button
              onClick={handleStartNew}
              style={{
                padding: '10px 20px',
                background: 'rgba(124,111,247,0.12)',
                border: '1px solid rgba(124,111,247,0.35)',
                borderRadius: 'var(--radius-md)',
                color: 'var(--agent-chief)',
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
                fontFamily: fontUi
              }}
            >
              {t.startNew || '→ Start New'}
            </button>
          </div>
        </div>
      </div>
    )
  }

  return <div />
}
